# Generated by Django 3.2.12 on 2022-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('video', models.FileField(upload_to='Youtube')),
                ('thumbnail', models.ImageField(upload_to='Youtube_thumnail')),
            ],
        ),
    ]
