# Generated by Django 3.2.12 on 2022-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('intro', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
